/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as CandidateIndexRouteImport } from './routes/candidate.index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as InterviewIdRouteImport } from './routes/interview.$id'
import { Route as AppUsageRouteImport } from './routes/_app/usage'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppCandidatesRouteImport } from './routes/_app/candidates'
import { Route as AppInterviewsIndexRouteImport } from './routes/_app/interviews.index'
import { Route as AppCandidatesIndexRouteImport } from './routes/_app/candidates.index'
import { Route as CandidateResultIdRouteImport } from './routes/candidate.result.$id'
import { Route as AppInterviewsNewRouteImport } from './routes/_app/interviews.new'
import { Route as AppInterviewsIdRouteImport } from './routes/_app/interviews.$id'
import { Route as AppCandidatesNewRouteImport } from './routes/_app/candidates.new'
import { Route as AppCandidatesIdRouteImport } from './routes/_app/candidates.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const InterviewIdRoute = InterviewIdRouteImport.update({
  id: '/interview/$id',
  path: '/interview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsIndexRoute = AppInterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesIndexRoute = AppCandidatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCandidatesRoute,
} as any)
const CandidateResultIdRoute = CandidateResultIdRouteImport.update({
  id: '/candidate/result/$id',
  path: '/candidate/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInterviewsNewRoute = AppInterviewsNewRouteImport.update({
  id: '/interviews/new',
  path: '/interviews/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsIdRoute = AppInterviewsIdRouteImport.update({
  id: '/interviews/$id',
  path: '/interviews/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesNewRoute = AppCandidatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCandidatesRoute,
} as any)
const AppCandidatesIdRoute = AppCandidatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCandidatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/candidates': typeof AppCandidatesRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/usage': typeof AppUsageRoute
  '/interview/$id': typeof InterviewIdRoute
  '/candidate/': typeof CandidateIndexRoute
  '/candidates/$id': typeof AppCandidatesIdRoute
  '/candidates/new': typeof AppCandidatesNewRoute
  '/interviews/$id': typeof AppInterviewsIdRoute
  '/interviews/new': typeof AppInterviewsNewRoute
  '/candidate/result/$id': typeof CandidateResultIdRoute
  '/candidates/': typeof AppCandidatesIndexRoute
  '/interviews/': typeof AppInterviewsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/usage': typeof AppUsageRoute
  '/interview/$id': typeof InterviewIdRoute
  '/': typeof AppIndexRoute
  '/candidate': typeof CandidateIndexRoute
  '/candidates/$id': typeof AppCandidatesIdRoute
  '/candidates/new': typeof AppCandidatesNewRoute
  '/interviews/$id': typeof AppInterviewsIdRoute
  '/interviews/new': typeof AppInterviewsNewRoute
  '/candidate/result/$id': typeof CandidateResultIdRoute
  '/candidates': typeof AppCandidatesIndexRoute
  '/interviews': typeof AppInterviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/candidates': typeof AppCandidatesRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/usage': typeof AppUsageRoute
  '/interview/$id': typeof InterviewIdRoute
  '/_app/': typeof AppIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/_app/candidates/$id': typeof AppCandidatesIdRoute
  '/_app/candidates/new': typeof AppCandidatesNewRoute
  '/_app/interviews/$id': typeof AppInterviewsIdRoute
  '/_app/interviews/new': typeof AppInterviewsNewRoute
  '/candidate/result/$id': typeof CandidateResultIdRoute
  '/_app/candidates/': typeof AppCandidatesIndexRoute
  '/_app/interviews/': typeof AppInterviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/candidates'
    | '/profile'
    | '/reports'
    | '/usage'
    | '/interview/$id'
    | '/candidate/'
    | '/candidates/$id'
    | '/candidates/new'
    | '/interviews/$id'
    | '/interviews/new'
    | '/candidate/result/$id'
    | '/candidates/'
    | '/interviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/profile'
    | '/reports'
    | '/usage'
    | '/interview/$id'
    | '/'
    | '/candidate'
    | '/candidates/$id'
    | '/candidates/new'
    | '/interviews/$id'
    | '/interviews/new'
    | '/candidate/result/$id'
    | '/candidates'
    | '/interviews'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/candidates'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/usage'
    | '/interview/$id'
    | '/_app/'
    | '/candidate/'
    | '/_app/candidates/$id'
    | '/_app/candidates/new'
    | '/_app/interviews/$id'
    | '/_app/interviews/new'
    | '/candidate/result/$id'
    | '/_app/candidates/'
    | '/_app/interviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  InterviewIdRoute: typeof InterviewIdRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  CandidateResultIdRoute: typeof CandidateResultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/interview/$id': {
      id: '/interview/$id'
      path: '/interview/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof InterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates': {
      id: '/_app/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews/': {
      id: '/_app/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof AppInterviewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates/': {
      id: '/_app/candidates/'
      path: '/'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AppCandidatesIndexRouteImport
      parentRoute: typeof AppCandidatesRoute
    }
    '/candidate/result/$id': {
      id: '/candidate/result/$id'
      path: '/candidate/result/$id'
      fullPath: '/candidate/result/$id'
      preLoaderRoute: typeof CandidateResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/interviews/new': {
      id: '/_app/interviews/new'
      path: '/interviews/new'
      fullPath: '/interviews/new'
      preLoaderRoute: typeof AppInterviewsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews/$id': {
      id: '/_app/interviews/$id'
      path: '/interviews/$id'
      fullPath: '/interviews/$id'
      preLoaderRoute: typeof AppInterviewsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates/new': {
      id: '/_app/candidates/new'
      path: '/new'
      fullPath: '/candidates/new'
      preLoaderRoute: typeof AppCandidatesNewRouteImport
      parentRoute: typeof AppCandidatesRoute
    }
    '/_app/candidates/$id': {
      id: '/_app/candidates/$id'
      path: '/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AppCandidatesIdRouteImport
      parentRoute: typeof AppCandidatesRoute
    }
  }
}

interface AppCandidatesRouteChildren {
  AppCandidatesIdRoute: typeof AppCandidatesIdRoute
  AppCandidatesNewRoute: typeof AppCandidatesNewRoute
  AppCandidatesIndexRoute: typeof AppCandidatesIndexRoute
}

const AppCandidatesRouteChildren: AppCandidatesRouteChildren = {
  AppCandidatesIdRoute: AppCandidatesIdRoute,
  AppCandidatesNewRoute: AppCandidatesNewRoute,
  AppCandidatesIndexRoute: AppCandidatesIndexRoute,
}

const AppCandidatesRouteWithChildren = AppCandidatesRoute._addFileChildren(
  AppCandidatesRouteChildren,
)

interface AppRouteChildren {
  AppCandidatesRoute: typeof AppCandidatesRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInterviewsIdRoute: typeof AppInterviewsIdRoute
  AppInterviewsNewRoute: typeof AppInterviewsNewRoute
  AppInterviewsIndexRoute: typeof AppInterviewsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCandidatesRoute: AppCandidatesRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppUsageRoute: AppUsageRoute,
  AppIndexRoute: AppIndexRoute,
  AppInterviewsIdRoute: AppInterviewsIdRoute,
  AppInterviewsNewRoute: AppInterviewsNewRoute,
  AppInterviewsIndexRoute: AppInterviewsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  InterviewIdRoute: InterviewIdRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  CandidateResultIdRoute: CandidateResultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
